### PR TITLE
Add full json schema

### PR DESCRIPTION
**Pull request by radchukd**

### CODE REVIEW

**Comment by sdairs** [comment]
Something not quite working after the last change, preview build shows an error for all schema templates (you can still Save & they work fine despite the error)

image

**Comment by radchukd** [comment]
@sdairs I don't have any errors, try `rm -rf node_modules && npm install && cd packages/mockingbird/ && npm run build && cd ../../apps/web/ && npm run dev`

**Comment by sdairs** [comment]
@radchukd this is on the Vercel preview build https://mockingbird-web-git-feat-add-full-jsonschema-tinybird.vercel.app/

**Comment by radchukd** [comment]
@sdairs I don't have this error there as well. I tried tinybird and upstash and all the schemas. 🙃

**Comment by sdairs** [comment]
It's stopped doing it for me now as well 🤨

**Review by sdairs — APPROVED** [review]

**Pull request merged**
